#pragma once

// From glfw3.h

#define HZ_GAMEPAD_BUTTON_A               0
#define HZ_GAMEPAD_BUTTON_B               1
#define HZ_GAMEPAD_BUTTON_X               2
#define HZ_GAMEPAD_BUTTON_Y               3
#define HZ_GAMEPAD_BUTTON_LEFT_BUMPER     4
#define HZ_GAMEPAD_BUTTON_RIGHT_BUMPER    5
#define HZ_GAMEPAD_BUTTON_BACK            6
#define HZ_GAMEPAD_BUTTON_START           7
#define HZ_GAMEPAD_BUTTON_GUIDE           8
#define HZ_GAMEPAD_BUTTON_LEFT_THUMB      9
#define HZ_GAMEPAD_BUTTON_RIGHT_THUMB     10
#define HZ_GAMEPAD_BUTTON_DPAD_UP         11
#define HZ_GAMEPAD_BUTTON_DPAD_RIGHT      12
#define HZ_GAMEPAD_BUTTON_DPAD_DOWN       13
#define HZ_GAMEPAD_BUTTON_DPAD_LEFT       14
#define HZ_GAMEPAD_BUTTON_LAST            HZ_GAMEPAD_BUTTON_DPAD_LEFT

#define HZ_GAMEPAD_BUTTON_CROSS       HZ_GAMEPAD_BUTTON_A
#define HZ_GAMEPAD_BUTTON_CIRCLE      HZ_GAMEPAD_BUTTON_B
#define HZ_GAMEPAD_BUTTON_SQUARE      HZ_GAMEPAD_BUTTON_X
#define HZ_GAMEPAD_BUTTON_TRIANGLE    HZ_GAMEPAD_BUTTON_Y


#define HZ_GAMEPAD_AXIS_LEFT_X        0
#define HZ_GAMEPAD_AXIS_LEFT_Y        1
#define HZ_GAMEPAD_AXIS_RIGHT_X       2
#define HZ_GAMEPAD_AXIS_RIGHT_Y       3
#define HZ_GAMEPAD_AXIS_LEFT_TRIGGER  4
#define HZ_GAMEPAD_AXIS_RIGHT_TRIGGER 5
#define HZ_GAMEPAD_AXIS_LAST          HZ_GAMEPAD_AXIS_RIGHT_TRIGGER